### ISSUE TITLE
Is it can be as an app in version Odoo 11?

### ISSUE THREAD

**Issue by tianyan10086** [zeroheure/odoo-seo#1]
Is it can be as an app in version Odoo 11?

**Comment by zeroheure** [comment]
All of these is not ready yet. Some modules works in 10, some not. I plan to migrate code to Odoo 11 once everything will be finished (very soon). As it lack some documentation for now, you shouldn't expect much from these modules if you don't understand how Page Rank works and what is PageRank Sculpting.
First, you should install the canonical_url module from OCA, and disable all product sorting in the shop to avoid duplicate content in search engines index. The canonical_url module will be quickly available to Odoo 11 once the 10 migration will be finished. See https://github.com/OCA/website/pull/449 

TODO
- documentation : what's the problem in Odoo, what to expect from those modules, some links to reference doc.
- automate obfuscated links
